export type Screen = {
  ref: string;
  title: string;
  group: string;
  path: string;
};
export const screens: Screen[] = [
  {
    ref: "A1",
    title: "Landing page",
    group: "Site public",
    path: "/",
  },
  {
    ref: "A2",
    title: "Fonctionnalités",
    group: "Site public",
    path: "/fonctionnalites",
  },
  {
    ref: "A3",
    title: "Tarifs",
    group: "Site public",
    path: "/tarifs",
  },
  {
    ref: "A4",
    title: "Connexion",
    group: "Site public",
    path: "/connexion",
  },
  {
    ref: "A5",
    title: "Inscription",
    group: "Site public",
    path: "/inscription",
  },
  {
    ref: "A6",
    title: "Mot de passe oublié",
    group: "Site public",
    path: "/mot-de-passe-oublie",
  },
  {
    ref: "A7",
    title: "Pages légales",
    group: "Site public",
    path: "/legal/mentions",
  },
  {
    ref: "A8",
    title: "Contact et support",
    group: "Site public",
    path: "/contact",
  },
  {
    ref: "B1",
    title: "Bienvenue",
    group: "Mise en route",
    path: "/bienvenue",
  },
  {
    ref: "B2",
    title: "Connexion Meta",
    group: "Mise en route",
    path: "/configuration/meta",
  },
  {
    ref: "B3",
    title: "Sélection du Business Manager",
    group: "Mise en route",
    path: "/configuration/business-manager",
  },
  {
    ref: "B4",
    title: "Sélection du compte publicitaire",
    group: "Mise en route",
    path: "/configuration/comptes",
  },
  {
    ref: "B5",
    title: "Page Facebook et compte Instagram",
    group: "Mise en route",
    path: "/configuration/pages",
  },
  {
    ref: "B6",
    title: "Pixel et événement de conversion",
    group: "Mise en route",
    path: "/configuration/pixel",
  },
  {
    ref: "B7",
    title: "Formulaire",
    group: "Business Brain",
    path: "/configuration/entreprise",
  },
  {
    ref: "B8",
    title: "Analyse automatique du site",
    group: "Business Brain",
    path: "/configuration/analyse-site",
  },
  {
    ref: "B9",
    title: "Récapitulatif",
    group: "Business Brain",
    path: "/configuration/recapitulatif",
  },
  {
    ref: "B10",
    title: "Choix du plan et paiement",
    group: "Business Brain",
    path: "/configuration/plan",
  },
  {
    ref: "B11",
    title: "Onboarding terminé",
    group: "Business Brain",
    path: "/configuration/terminee",
  },
  {
    ref: "C1.1",
    title: "Tableau de bord",
    group: "Tableau de bord",
    path: "/app/tableau-de-bord",
  },
  {
    ref: "C1.2",
    title: "Sélecteur de compte",
    group: "Tableau de bord",
    path: "/app/comptes",
  },
  {
    ref: "C2.1",
    title: "Fil des recommandations",
    group: "Agent",
    path: "/app/agent",
  },
  {
    ref: "C2.2",
    title: "Détail d'une recommandation",
    group: "Agent",
    path: "/app/agent/recommandation",
  },
  {
    ref: "C2.3",
    title: "Modale de confirmation",
    group: "Agent",
    path: "/app/agent/confirmation",
  },
  {
    ref: "C2.4",
    title: "Historique — réel contre estimé",
    group: "Agent",
    path: "/app/agent/historique",
  },
  {
    ref: "C2.5",
    title: "Réglages de l'agent",
    group: "Agent",
    path: "/app/agent/reglages",
  },
  {
    ref: "C3.1",
    title: "Tableau des campagnes",
    group: "Gestionnaire",
    path: "/app/campagnes",
  },
  {
    ref: "C3.2",
    title: "Ensembles de publicités",
    group: "Gestionnaire",
    path: "/app/ensembles",
  },
  {
    ref: "C3.3",
    title: "Publicités",
    group: "Gestionnaire",
    path: "/app/publicites",
  },
  {
    ref: "C4.1",
    title: "Choix du mode",
    group: "Constructeur",
    path: "/app/creation/mode",
  },
  {
    ref: "C4.2",
    title: "Brief et états",
    group: "Constructeur",
    path: "/app/creation/brief",
  },
  {
    ref: "C4.3",
    title: "Proposition de structure de l'agent",
    group: "Constructeur",
    path: "/app/creation/proposition",
  },
  {
    ref: "C4.4",
    title: "Construction manuelle — campagne",
    group: "Constructeur",
    path: "/app/creation/campagne",
  },
  {
    ref: "C4.5",
    title: "Ensembles et ciblage",
    group: "Constructeur",
    path: "/app/creation/ciblage",
  },
  {
    ref: "C4.6",
    title: "Publicités et créatives",
    group: "Constructeur",
    path: "/app/creation/creatives",
  },
  {
    ref: "C4.7",
    title: "Textes publicitaires",
    group: "Constructeur",
    path: "/app/creation/textes",
  },
  {
    ref: "C4.8",
    title: "Prévisualisation multi-placements",
    group: "Constructeur",
    path: "/app/creation/apercu",
  },
  {
    ref: "C4.9",
    title: "Récapitulatif et publication",
    group: "Constructeur",
    path: "/app/creation/publication",
  },
  {
    ref: "C5.1",
    title: "Point de départ et brief créatif",
    group: "Studio",
    path: "/app/studio",
  },
  {
    ref: "C5.2",
    title: "Génération de textes",
    group: "Studio",
    path: "/app/studio/textes",
  },
  {
    ref: "C5.3",
    title: "Génération de visuels",
    group: "Studio",
    path: "/app/studio/visuels",
  },
  {
    ref: "C5.4",
    title: "Génération de vidéos courtes",
    group: "Studio",
    path: "/app/studio/videos",
  },
  {
    ref: "C5.5",
    title: "Galerie de résultats",
    group: "Studio",
    path: "/app/studio/resultats",
  },
  {
    ref: "C5.6",
    title: "Retouche et déclinaisons",
    group: "Studio",
    path: "/app/studio/retouche",
  },
  {
    ref: "C5.7",
    title: "Bibliothèque personnelle",
    group: "Studio",
    path: "/app/studio/bibliotheque",
  },
  {
    ref: "C6.1",
    title: "Classement des créatives",
    group: "Analyse créative",
    path: "/app/analyse",
  },
  {
    ref: "C6.2",
    title: "Détail d'une créative",
    group: "Analyse créative",
    path: "/app/analyse/creative",
  },
  {
    ref: "C6.3",
    title: "Analyse par éléments",
    group: "Analyse créative",
    path: "/app/analyse/elements",
  },
  {
    ref: "C6.4",
    title: "Fatigue et cycle de vie",
    group: "Analyse créative",
    path: "/app/analyse/fatigue",
  },
  {
    ref: "C6.5",
    title: "Gagnants enterrés",
    group: "Analyse créative",
    path: "/app/analyse/gagnants",
  },
  {
    ref: "C6.6",
    title: "Propositions d’itérations",
    group: "Analyse créative",
    path: "/app/analyse/iterations",
  },
  {
    ref: "C8.1",
    title: "Recherche de publicités",
    group: "Intelligence marché",
    path: "/app/marche",
  },
  {
    ref: "C8.2",
    title: "Détail d’une publicité",
    group: "Intelligence marché",
    path: "/app/marche/publicite",
  },
  {
    ref: "C8.3",
    title: "Mes collections",
    group: "Intelligence marché",
    path: "/app/marche/collections",
  },
  {
    ref: "C8.4",
    title: "Détail d’une collection",
    group: "Intelligence marché",
    path: "/app/marche/collection",
  },
  {
    ref: "C8.5",
    title: "Lancer une analyse de marché",
    group: "Intelligence marché",
    path: "/app/marche/analyser",
  },
  {
    ref: "C8.6",
    title: "Rapport d’analyse de marché",
    group: "Intelligence marché",
    path: "/app/marche/analyse",
  },
  {
    ref: "C8.7",
    title: "Axes de communication recommandés",
    group: "Intelligence marché",
    path: "/app/marche/axes",
  },
  {
    ref: "C8.8",
    title: "Historique des analyses",
    group: "Intelligence marché",
    path: "/app/marche/historique",
  },
  {
    ref: "C9.1",
    title: "Liste des rapports",
    group: "Rapports",
    path: "/app/rapports",
  },
  {
    ref: "C9.2",
    title: "Composition d'un rapport",
    group: "Rapports",
    path: "/app/rapports/editeur",
  },
  {
    ref: "C9.3",
    title: "Modèles de rapport",
    group: "Rapports",
    path: "/app/rapports/modeles",
  },
  {
    ref: "C9.4",
    title: "Paramètres de partage",
    group: "Rapports",
    path: "/app/rapports/partage",
  },
  {
    ref: "C9.5",
    title: "Vue publique partagée",
    group: "Rapports",
    path: "/rapport/demo",
  },
  {
    ref: "C10.1",
    title: "Fiche entreprise",
    group: "Business Brain",
    path: "/app/business-brain",
  },
  {
    ref: "C10.2",
    title: "Produits et offres",
    group: "Business Brain",
    path: "/app/business-brain/produits",
  },
  {
    ref: "C10.3",
    title: "Historique des modifications",
    group: "Business Brain",
    path: "/app/business-brain/historique",
  },
  {
    ref: "C11.1",
    title: "Profil utilisateur",
    group: "Paramètres",
    path: "/app/parametres",
  },
  {
    ref: "C11.2",
    title: "Comptes Meta connectés",
    group: "Paramètres",
    path: "/app/parametres/meta",
  },
  {
    ref: "C11.3",
    title: "Abonnement et plan",
    group: "Paramètres",
    path: "/app/parametres/abonnement",
  },
  {
    ref: "C11.4",
    title: "Crédits",
    group: "Paramètres",
    path: "/app/parametres/credits",
  },
  {
    ref: "C11.5",
    title: "Historique de facturation",
    group: "Paramètres",
    path: "/app/parametres/facturation",
  },
  {
    ref: "C11.6",
    title: "Notifications",
    group: "Paramètres",
    path: "/app/parametres/notifications",
  },
  {
    ref: "C11.7",
    title: "Équipe et accès",
    group: "Paramètres",
    path: "/app/parametres/equipe",
  },
  {
    ref: "C11.8",
    title: "Déconnexion et suppression de compte",
    group: "Paramètres",
    path: "/app/parametres/securite",
  },
  {
    ref: "C7.1",
    title: "Règles automatisées",
    group: "Règles automatisées",
    path: "/app/regles",
  },
  {
    ref: "C7.2",
    title: "Créer une règle",
    group: "Règles automatisées",
    path: "/app/regles/creer",
  },
  {
    ref: "C7.3",
    title: "Historique des règles",
    group: "Règles automatisées",
    path: "/app/regles/historique",
  },
  {
    ref: "verify",
    title: "Vérifiez votre boîte e-mail",
    group: "Public",
    path: "/verification",
  },
  {
    ref: "reset",
    title: "Nouveau mot de passe",
    group: "Public",
    path: "/nouveau-mot-de-passe",
  },
  {
    ref: "terms",
    title: "Conditions générales",
    group: "Public",
    path: "/legal/conditions",
  },
  {
    ref: "privacy",
    title: "Confidentialité",
    group: "Public",
    path: "/legal/confidentialite",
  },
  {
    ref: "cookies",
    title: "Cookies",
    group: "Public",
    path: "/legal/cookies",
  },
  {
    ref: "directory",
    title: "Toutes les pages",
    group: "Public",
    path: "/parcours",
  },
];
export const route = (ref: string) =>
  screens.find((s) => s.ref === ref)?.path ?? "/app/tableau-de-bord";
